### ISSUE TITLE
Screensaver inhibition does not work

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.github.thestr4ng3r.Chiaki#1]
Screensaver (lock screen) gets activated after some time when playing with a PS4 controller using Chiaki, at least on my system with GNOME Wayland session. It should be inhibited and there is `--talk-name=org.freedesktop.ScreenSaver` present in the Flatpak manifest, so maybe this is an upstream Chiaki issue.

**Comment by nedrichards** [comment]
This has just been renamed over here https://github.com/flathub/re.chiaki.Chiaki so do file either there or upstream
